<script setup lang="ts">
import { computed, ref, watch } from 'vue'

// -------------------------
// Types & constants
// -------------------------

type CategoryKey = 'all' | 'tools' | 'apps' | 'toys' | 'plugins' | 'experiments' | 'other'

type ProjectItem = {
  title: string
  description: string
  image: string
  slug: string
  url?: string
  category: CategoryKey
}

type ProjectViewItem = ProjectItem & { href: string }

type ProjectGroups = Partial<Record<Exclude<CategoryKey, 'all'>, ProjectViewItem[]>>

const tabOrder: CategoryKey[] = ['all', 'tools', 'apps', 'toys', 'plugins', 'experiments', 'other']

// -------------------------
// Content: load page + projects
// -------------------------

const { locale, t } = useI18n()
const { data: page } = await useAsyncData('projects-page', () => {
  return queryCollection(`pages_${locale.value}`).path(`/${locale.value}/projects`).first()
})

if (!page.value) {
  throw createError({
    statusCode: 404,
    statusMessage: 'Page not found',
    fatal: true
  })
}

const { data: projects } = await useAsyncData('projects', () => {
  return queryCollection(`projects_${locale.value}`).all()
})

// -------------------------
// Tabs state (bind by key instead of index)
// -------------------------

const currentCategory = ref<CategoryKey>('all')

// Tabs list is auto-generated by present categories, but kept in stable ordering
const tabs = computed<CategoryKey[]>(() => {
  const list = (projects.value ?? []) as any[]
  const present = new Set<CategoryKey>()

  for (const raw of list) {
    present.add(String(raw.category ?? 'other') as CategoryKey)
  }

  return tabOrder.filter(k => k === 'all' || present.has(k))
})

const tabItems = computed(() => {
  return tabs.value.map(cat => ({ label: t(`projects.categories.${cat}`), value: cat }))
})

// If currentCategory becomes unavailable (e.g. content changed), fallback to 'all'
watch(tabs, (next) => {
  if (!next.includes(currentCategory.value)) {
    currentCategory.value = 'all'
  }
}, { immediate: true })

// -------------------------
// Normalize content items
// - "file name as slug": slug from meta.path or stem when frontmatter slug is absent
// - precompute href: url ?? /projects/<slug>
// -------------------------

const getSlugFromRaw = (raw: any) => {
  return String(
    raw.slug
    ?? raw.meta?.path?.split('/').pop()
    ?? raw.stem?.split('/').pop()
    ?? ''
  )
}

const normalizeProjectItem = (raw: any): ProjectViewItem => {
  const slug = getSlugFromRaw(raw)
  const url = raw.url ? String(raw.url) : undefined

  return {
    title: String(raw.title ?? ''),
    description: String(raw.description ?? ''),
    image: String(raw.image ?? ''),
    slug,
    url,
    category: (String(raw.category ?? 'other') as CategoryKey),
    href: url || `/${locale.value}/projects/${slug}`
  }
}

const normalizedProjects = computed<ProjectViewItem[]>(() => {
  const list = (projects.value ?? []) as any[]
  return list
    .map(normalizeProjectItem)
    .filter(p => p.title && p.slug)
})

// -------------------------
// ViewModel: group & filter for rendering
// -------------------------

const groupedProjects = computed<ProjectGroups>(() => {
  const groups: ProjectGroups = {}

  const list = [...normalizedProjects.value].sort((a, b) => a.slug.localeCompare(b.slug))
  for (const project of list) {
    const key = project.category as Exclude<CategoryKey, 'all'>
    ;(groups[key] ||= []).push(project)
  }

  return groups
})

const visibleGroups = computed<ProjectGroups>(() => {
  const groups = groupedProjects.value
  const ordered: ProjectGroups = {}

  for (const cat of tabOrder) {
    if (cat === 'all') continue

    if (currentCategory.value !== 'all' && currentCategory.value !== cat) continue

    const items = groups[cat]
    if (items?.length) {
      ordered[cat] = items
    }
  }

  return ordered
})

// -------------------------
// SEO
// -------------------------

const { global } = useAppConfig()

useSeoMeta({
  title: page.value?.seo?.title || page.value?.title,
  ogTitle: page.value?.seo?.title || page.value?.title,
  description: page.value?.seo?.description || page.value?.description,
  ogDescription: page.value?.seo?.description || page.value?.description
})
</script>

<template>
  <UPage v-if="page">
    <UPageHero
      :title="page.title"
      :description="page.description"
      :links="page.links"
      :ui="{
        title: '!mx-0 text-left',
        description: '!mx-0 text-left',
        links: 'justify-start'
      }"
    >
      <template #links>
        <div
          v-if="page.links"
          class="flex items-center gap-2"
        >
          <UButton
            :label="page.links[0]?.label"
            :to="global.githubLink"
            v-bind="page.links[0]"
          />
          <UButton
            :to="`mailto:${global.email}`"
            v-bind="page.links[1]"
          />
        </div>
      </template>
    </UPageHero>

    <UPageSection>
      <UTabs
        v-model="currentCategory"
        :items="tabItems"
        default-value="all"
      />

      <div class="mt-8 space-y-12">
        <template v-if="Object.keys(visibleGroups).length === 0">
          <div class="text-center py-12">
            <p class="text-muted">
              {{ t('projects.empty') }}
            </p>
          </div>
        </template>
        <template v-else>
          <div
            v-for="(group, category) in visibleGroups"
            :key="category"
          >
            <h2 class="text-2xl font-bold mb-4">
              {{ t(`projects.categories.${category}`) }}
            </h2>

            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Motion
                v-for="(project, index) in group"
                :key="project.title"
                :initial="{ opacity: 0, transform: 'translateY(10px)' }"
                :while-in-view="{ opacity: 1, transform: 'translateY(0)' }"
                :transition="{ delay: 0.1 * index }"
                :in-view-options="{ once: true }"
                class="h-full"
              >
                <UCard
                  class="
                    flex flex-col h-full group
                    ring-1 ring-gray-200 dark:ring-gray-800
                    hover:ring-primary-500 dark:hover:ring-primary-400
                    transition-shadow duration-200
                    divide-y
                  "
                  :ui="{
                    body: 'flex-1'
                  }"
                >
                  <template #header>
                    <a
                      :href="project.href"
                      target="_blank"
                      rel="noopener"
                      class="block h-48 overflow-hidden"
                    >
                      <img
                        :src="project.image"
                        :alt="project.title"
                        class="object-cover w-full h-full rounded-t-lg group-hover:scale-105 transition-transform duration-300"
                      >
                    </a>
                  </template>

                  <h3 class="font-semibold text-lg">
                    {{ project.title }}
                  </h3>
                  <p class="text-muted mt-1 text-sm">
                    {{ project.description }}
                  </p>

                  <template #footer>
                    <div class="flex justify-end items-center">
                      <UButton
                        :to="project.href"
                        target="_blank"
                        rel="noopener"
                        variant="link"
                        :padded="false"
                      >
                        {{ t('projects.viewProject') }}
                        <UIcon
                          name="i-lucide-arrow-right"
                          class="w-4 h-4 ml-1 opacity-0 group-hover:opacity-100 transition-opacity"
                        />
                      </UButton>
                    </div>
                  </template>
                </UCard>
              </Motion>
            </div>
          </div>
        </template>
      </div>
    </UPageSection>
  </UPage>
</template>
